In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import scipy.io as sio

In [51]:
IMG_SIZE = 28*28
images = sio.loadmat('hw7_data/mnist_data/images.mat', mat_dtype=True)['images']
flattened_images = np.reshape(images, (IMG_SIZE, 60000)).T

In [81]:
def lloyd_objective_function(clusters, means):
    total = 0
    for c, mu in zip(clusters, means):
        for sample in c:
            total += np.linalg.norm(sample - mu) ** 2
            
def fit_cluster(x, means, original_cluster):
    best_cluster, min_cost = original_cluster, np.linalg(x - means[original_cluster])**2
    for i, mu in enumerate(means):
        cost = np.linalg(x - mu) ** 2
        if cost < min_cost:
            best_cluster, min_cost = i, cost
    return best_cluster, min_cost
    
def lloyd(k, images, max_iterations=100, min_change=0):
    # Forgy method initialization
    seeds = images[np.random.choice(images.shape[0], k, replace=False), :]
    
    means = []
    for i, s in enumerate(seeds):
        means[i] = np.reshape(s, (1, IMG_SIZE))
        
    clusters = {}
    for i in range(len(means)):
        clusters[i] = []
    
    for img in images:
        clusters[fit_cluster(img, means, 0)].append(img)
        
    i, diffs = 0, float('inf')
    while i < max_iterations and diffs > min_change: # also check for assignment changes
        # used by phase 2
        diffs = []
        
        # phase 1
        means = []
        for c in clusters:
            means.append(np.mean(c, axis=0))
        
        # phase 2
        new_clusters = {}
        for i in range(len(clusters)):
            new_clusters[i] = []
            
        for ci, cluster in clusters.iteritems():
            for x in cluster:
                new_ci = fit_cluster(x, means, ci)
                new_clusters[new_ci].apppend(x)
                if new_ci != ci:
                    diffs += 1
                
        clusters = new_clusters
        
        i += 1
    return clusters

2598.14183601


In [50]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
a = np.array([[1], [2], [3]]).T
print a.shape, b.shape
print b - a

(1, 3) (3, 3)
[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [74]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
A[np.random.choice(A.shape[0], 4, replace=False), :]

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6]])

In [79]:
print A, A.shape
np.mean(A, axis=0)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


array([ 5.5,  6.5,  7.5])

In [80]:
arr = [1, 2, 3, 4, 5]
for i, j in enumerate(arr):
    print i, j

0 1
1 2
2 3
3 4
4 5
